environment: {}
parameters: {}
packages:
  - name: pagerating
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: capture-page-rating
        binary: false
        main: ''
        runtime: 'python:default'
        web: true
        parameters: {}
        environment:
          DB_HOST: "${DB_HOST}"
          DB_USER: "${DB_USER}"
          DB_DATABASE: "${DB_DATABASE}"
          DB_PORT: "${DB_PORT}"
          DB_PASSWORD: "${DB_PASSWORD}"
        annotations: {}
        limits: {}
